### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by bendulum** [bkrem/react-d3-tree#12]
For large data sets with loads of parallel nodes the tree width (or height) gets very big.
Spacing could be optimized in such cases (margins between the nodes).

It would also be nice to be able to provide a custom render function for each node.

Anyways, nice job! I'm looking forward to what else you might add in the future.

**Comment by bkrem** [comment]
Thank you for the suggestions @bendulum, appreciate the input since I need to know what people's typical data sets/use cases would be for the component.

Exposing a prop for custom node margins is on the list for sure, can you describe for me what exactly you mean by custom render function in this context? I.e. what would the differences in rendered nodes be?

**Comment by bkrem** [comment]
Thanks for detailing out your suggestion @bendulum! 

Exposing a custom node spacing/margin function is now in the roadmap (#13).

I'll have to think some more on how to best implement discretionary rendering of individual nodes as you suggested and how I should prioritise it compared to other possible features. 
In the meantime, feel free to submit a feature PR if you want this and I'll be happy to merge it! :)
