### ISSUE TITLE
Merging trees via "spouse" nodes

### ISSUE THREAD

**Issue by dmitrydomanski** [bkrem/react-d3-tree#139]
Thank you for your beautiful work!

Say, I have two ancestor's trees - of a husband and a wife. Is there a way to merge them so both could be visible on the same canvas, merged in a "marriage" point?

**Comment by bkrem** [comment]
Hi @dmitrydomanski,

Apologies for the delay. This might be possible heuristically (as in you arrange two instances of `react-d3-tree` in a way that they intersect at a certain point), but not technically since D3's `tree` function needs a clearly defined single root node to build the graph from; in this case there would be two.

Even if you said "the husband root node is the de facto root node", all of the wife's nodes (including the root node) would be seen as children of the node in the husband graph where they intersect, meaning the resulting layout would not be representative at all of what you're trying to visualise.

Sorry to not be much help on that, but I hope it was a useful tool for you nonetheless! :)
