### ISSUE TITLE
I'm trying to adjust the stroke width of the square svg for all nodes

### ISSUE THREAD

**Issue by Robert-Fish** [bkrem/react-d3-tree#180]
`
styles={{
            nodes: {
              strokeWidth: 0.4
            }
          }}
`

What am i doing wrong?

**Comment by bkrem** [comment]
@Robert-Fish I think the issue here is that you're using `props.nodeSvgShape` (which takes a higher priority than the styling via `props.styles`), but still styling via `props.styles` rather than passing the props to your svgShape(s) directly via `nodeSvgShape.shapeProps`. I think what you want is:

```jsx
<Tree
  // ...
  nodeSvgShape={{
    shape: "rect",
    shapeProps: {
      fill: "green",
      width: "20px",
      height: "20px",
      x: "-10px",
      y: "-10px",
      strokeWidth: 5
    }
  }}
  // ...
/>
```

I created an example on codesandbox too: https://codesandbox.io/s/jn572q8p8w

I also realise that the documentation around styling is obtuse for `v1.x`, so apologies if that tripped you up. I'm aiming for a significantly simpler and clearer styling API for `v2.x`.

Closing but if the issue still persists feel free to reopen
