### ISSUE TITLE
Failed prop type: The prop `name` is marked as required in `t`, but its value is `undefined`.

### ISSUE THREAD

**Issue by Robert-Fish** [bkrem/react-d3-tree#183]
Hi i was wondering if you could explain why i'm receiving this issue. For context, i'm mapping an object from my redux store as props.

**Comment by vprefournier** [comment]
I have the same problem, did you find a workaround or a solution?

**Comment by bkrem** [comment]
@Robert-Fish @vprefournier 

Yeah this was a remnant of the original use case this lib was built on top of, where a name for each node was required unconditionally.

Since this seems to be a significant annoyance and wouldn't cause a breaking changes if removed I'll publish fix version in a few minutes that removes the `isRequired` on the node name propType.

**Comment by bkrem** [comment]
Published as [1.12.4](https://github.com/bkrem/react-d3-tree/releases/tag/v1.12.4). 

This should no longer be an issue regardless of your `data`'s shape :)

Feel free to reopen if the issue does persist.
