### ISSUE TITLE
multiple parent nodes

### ISSUE THREAD

**Issue by faizalmrub** [bkrem/react-d3-tree#205]
Thank you for taking the time to report an issue with react-d3-tree!  

Feel free to delete any questions that do not apply.

## Are you reporting a bug, or opening a feature request?
No. 
  
How do I implement multiple parent nodes pointing to same child node?  Also how do I implement multiple start root nodes?

Thanks

**Comment by yoyoyohamapi** [comment]
+1

**Comment by anarkafkas** [comment]
+1

**Comment by bkrem** [comment]
Hi @faizalmrub,

Sorry it's taken me this long to reply, I've finally found a good chunk of time to spend on this library again.

I believe what you're asking isn't possible via `D3`'s `tree`, since the tree is essentially a directed acyclic graph (DAG), i.e. it does not allow for circular references.

For example, if you had `root node -> 2 intermediate nodes (which both link to the same child node) -> 1 double linked child node`, this effectively creates a circular reference between the two intermediate nodes.

Also important to note: `D3`'s `tree` function by definition only accepts a single root node per tree.
