### ISSUE TITLE
[Question] How to conditionally style link based on connected node

### ISSUE THREAD

**Issue by raytangRT** [bkrem/react-d3-tree#214]
Hi, 

Can I change the link stroke color based on some attributes on the connected nodes

Thanks

**Comment by Jaleed96** [comment]
I'd like to know this as well.

**Comment by erfling** [comment]
+1

**Comment by karanbajaj2209** [comment]
+1

**Comment by nik10-mah** [comment]
I also need this. I think we can use **pathFunc** attribute and build our own custom function. But I am not able to find any implementation for that so not able to figure out as how to do that

**Comment by sibalajp** [comment]
related [#155](https://github.com/bkrem/react-d3-tree/issues/155)

**Comment by SecurityAnalystWB** [comment]
I worked that :

file css
`.linkBase{
    stroke:#ccc !important;
}`


It worked

**Comment by bfreden** [comment]
Adding a css file entry changes all links. The component supports changing the style for all links without using a css file.

The request is to change select links.

**Comment by bfreden** [comment]
We found this component very useful but also would like to control the styling on some links.

I propose supporting new parentLinkprops and childrenLinkprops style porperties in the tree data. An example is below. The parentLinkprops style property would be applied to the link from the parent. The childrenLinkprops style property would be applied to the links to all children. The parentLinkprops property would take priority over the childrenLinkprops property.

In react-d3-tree@1.16.1: creating the <path> element in Link includes:
        style={{ ...this.state.initialStyle, ...styles }}
This could be (or something simpler):
        style={{ ...this.state.initialStyle, ...styles, ...parentNode.childrenLinkprops, ...childNode.parentLinkprops }}
I have not looked into how to get parentNode and childNode for the link.

const myTreeData = [
  {
    name: 'Parent Node',
    attributes: { ... },
    nodeSvgShape: {
      shapeProps: {
        fill: 'blue',
      },
    },
    childrenLinkprops: {
      fill: 'blue',
    },
    children: [
      {
        name: 'Inner Node',
        attributes: { ... },
        nodeSvgShape: {
          shape: 'rect',
          shapeProps: {
            width: 20,
            height: 20,
            x: -10,
            y: -10,
            fill: 'red',
          },
        },
        parentLinkprops: {
          fill: 'red',
        },
      },
      {
        name: 'Level 2: B',
      },
    ],
  },
];

**Comment by dcanfield** [comment]
I also need this for my implementation.  As @nik10-mah mentioned, I hoped it might be possible to gain access to the _path_ element using the _pathFunc_ property in react-d3-tree.  I spent the afternoon looking through this, and am posting my results.  For reference please review the [SVG Paths element docs](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths).
Looking at a path element in the output of the tree using Chrome DevTools you will see something like this (assuming you have the default diagonal path selected):

`<path class="linkBase" d="M0,0 C0,70 358.75,70 358.75,140" data-source-id="6bb28a62-920b-4217-ae78-8d5878736734" data-target-id="1dc4a7b6-4356-4e48-a0c7-2972a4c46daa" style="opacity: 1;"></path>`

In my source code I added the pathFunc property to the react-d3-tree referencing my local function _getLink_

<Tree
	data={curAssessmentsTree}
	orientation={'vertical'}
	pathFunc={getLink}
/>

I was able to replicate the default diagonal path in my _getLink_ function:

const getLink = (linkData: any, orientation: any) => {
    const x1 = linkData.source.x
    const y1 = linkData.source.y
    const x2 = linkData.target.x
    const y2 = (linkData.target.y + linkData.source.y) / 2
    const x = linkData.target.x
    const y = linkData.target.y
    const d = `M${x1},${y1} C${x1},${y2} ${x2},${y2} ${x},${y}`
    return d
}

So, this would be great if what I wanted to do was customize the shape of the path element.  But because the _pathFunc_ property only gives me access to the _d_ attribute of the path element I can't change any of the other attributes of the path element, which is what I really want to do.

If the _pathFunc_ property actually gave me access to the path element, I might be able to something like this:

const getLink = (linkData: any, orientation: any) => {
    const x1 = linkData.source.x
    const y1 = linkData.source.y
    const x2 = linkData.target.x
    const y2 = (linkData.target.y + linkData.source.y) / 2
    const x = linkData.target.x
    const y = linkData.target.y
    const d = `M${x1},${y1} C${x1},${y2} ${x2},${y2} ${x},${y}`
    let customClass = ''
    if (linkData.target.myCustomColor === 'red') {
      customClass = 'myCustomClassRed'
    }
    return {class: customClass, d}
}

Which would evaluate to:

`<path class="myCustomClassRed" d="M0,0 C0,70 358.75,70 358.75,140" data-source-id="6bb28a62-920b-4217-ae78-8d5878736734" data-target-id="1dc4a7b6-4356-4e48-a0c7-2972a4c46daa" style="opacity: 1;"></path>`

For now I'm setting this aside, leaving the solution to better minds than mine.  I'm hoping some sort of solution could be implemented, because this is customizing the path element is an absolute necessity for my project.

**Comment by dcanfield** [comment]
Looks like there is PR for a solution similar to mine already in the works, and that adding custom class to links and nodes is WIP for the next major release:

https://github.com/bkrem/react-d3-tree/pull/179

Looking forward to the next release!  Any idea on the timeline?

**Comment by kkg335** [comment]
i also have to implement this in my code, can i get the solution for it?

**Comment by bkrem** [comment]
Hi everyone,

This is now possible via the [`pathClassFunc` prop](https://bkrem.github.io/react-d3-tree/docs/interfaces/_tree_types_.treeprops.html#pathclassfunc) in v1.17.1 and by extension in [v2.0.0](https://github.com/bkrem/react-d3-tree/releases). Usage examples can be found in the v2 readme's [Styling Links section](https://github.com/bkrem/react-d3-tree#styling-links).

If you're able to, I'd highly recommend checking out [v2](https://github.com/bkrem/react-d3-tree/), since it's a major overhaul of the docs, the library's internals (Typescript-first), and the API's flexibility (e.g. [`renderCustomNodeElement`](https://github.com/bkrem/react-d3-tree/#rendercustomnodeelement)).

Going forward, `v1` is considered deprecated and will only be updated for necessary patch releases. You can still find the old docs on the [`v1` branch](https://github.com/bkrem/react-d3-tree/tree/v1).

Apologies for the wait and thank you to everyone who provided workarounds/ad-hoc solutions 🙏 
v2 should've been done early this year, but I had to put unpaid projects (including open-source) aside for most of 2020 due to some "unexpected global events".
