### ISSUE TITLE
Can we make two branches merge?

### ISSUE THREAD

**Issue by tusharojha** [bkrem/react-d3-tree#325]
Hi @bkrem!
I really liked this package on npm but was curious if I can use this package to make some kind of merge between two branches similar to what git shows.

Like I have 2 children and want them to merge in one. Is it possible with this package?

**Comment by bkrem** [comment]
Hi @tusharojha,

Apologies for the delay in response here. I wasn't able to work on open source for most of 2020 for both professional and personal reasons, but I'm currently working through the open issue backlog for this library now that v2 has been released.

No, unfortunately this is not possible (I've tried 😄). This package is essentially a set of bindings to the underlying `d3.tree()` implementation, which does not allow for multiple parent nodes sharing a child node (i.e. circular references).

I will add this question to a new FAQ section in the docs, since it's a question that (understandably) comes up quite a lot.
