### ISSUE TITLE
Can we make tree chart with axes (x,y)

### ISSUE THREAD

**Issue by rizalgunawan** [bkrem/react-d3-tree#329]
Something like this

![image](https://user-images.githubusercontent.com/47345705/103640165-1c0eb200-4f82-11eb-8bff-66b3ae4fe7c8.png)

**Comment by bkrem** [comment]
Hi @rizalgunawan,

Thank you for this feature suggestion. I think this would definitely be an interesting use case for the library, but it's too specific to ship with the library itself, since it's supposed to be a (mostly) generic set of React bindings to the underlying `D3` functionality.

Implementing a chart like this should be possible with the library as is. If it isn't possible for some reason, I think the important discussion would be what is missing to make it happen.
