### ISSUE TITLE
Size limitations 

### ISSUE THREAD

**Issue by sanjanasrivastava** [bkrem/react-d3-tree#333]
Thank you for taking the time to report an issue with react-d3-tree!  

Feel free to delete any questions that do not apply.

## Are you reporting a bug, or opening a feature request?
Asking a general question
  
## What is the actual behavior/output?
Very slow performance when I try to use react-d3-tree with a JSON that has ~1500 nodes 

## What is the behavior/output you expect?
Less slow performance. My question is, what sizes should I expect slow performance for? 1500 nodes is large, but it's pretty small in the grand scheme of data structures (the JSON is 253 KB)

## Can you consistently reproduce the issue/create a reproduction case (e.g. on https://codesandbox.io)?
Sure 

## What version of react-d3-tree are you using?
The newest one

## If react-d3-tree crashed with a traceback, please paste the full traceback below.
It didn't

**Comment by bkrem** [comment]
Hi @sanjanasrivastava,

Are you using the `enableLegacyTransitions` prop? If so I'd recommend disabling this flag, since the legacy animations don't scale well beyond small/mid-size graphs (one of a number of reasons they're considered legacy now until a usable and performant alternative is ready).

Without animations enabled, the graph should be responsive, even for large datasets. 

E.g. the react repository example in the [demo](https://bkrem.github.io/react-d3-tree/) has 850+ nodes. 
I sized that example up to 1800+ nodes in an experiment just now, and apart from the initial load - during which `react-d3-tree` has to parse the entire tree to assign internal properties - it seemed to be business as usual.

If you're seeing significant perf issues in your graph without transitions enabled, I'd definitely be curious as to what the structure of your tree is (only if you're able to share of course).

**Comment by sanjanasrivastava** [comment]
Hi, I'm not using the `enableLegacyTransitions` prop but the tree still animates. Is this prop recent? I installed `react-d3-tree` 2-3 months ago.

**Comment by bkrem** [comment]
Right, yeah the component's API has gone through a major refactor for v2, which was released recently. You mentioned that you were using the newest version in the issue description, so I understood v2.

For v1 you'll need to **set the `transitionDuration` prop to `0`** (`enableLegacyTransitions: boolean` is v2 upwards). Once the animations are off, tree size should not significantly affect performance. 

If you do find a significant performance penalty (that's also present in v2), please open a separate bug ticket 👍 

The v1 branch is only receiving critical bug fixes going forward, so I'd recommend checking whether moving to v2 makes sense :) 
Moving from v1 to v2 should be fairly painless for most use cases, and the API is cleaner and more flexible/customizable now.

**I've added links to the v2 release notes (and to the v1 legacy docs) at the top of the readme [here](https://github.com/bkrem/react-d3-tree).**

**Comment by sanjanasrivastava** [comment]
Got it! Thanks :)
