### ISSUE TITLE
Each node different styles (width,height,styles) - Enhancement Feature

### ISSUE THREAD

**Issue by iqbalhussain931** [bkrem/react-d3-tree#35]
@bkrem same goes for the text attribute each node text/attributes can be positioned individually.

I hope you get my idea its pretty clear in the demo picture below :) waiting for you reply and what are you thoughts about this features :)
![demo-tree-part-1](https://user-images.githubusercontent.com/23423898/31328084-8ba6a33e-acec-11e7-997e-499a7b7f7edb.png)

**Comment by bkrem** [comment]
Hey @iqbalhussain931, this is great, thanks for taking the time to make a sketch! 👏 

Will try to get this implemented after work at some point this week, might take longer though if breaking changes can’t be avoided, i.e. it needs to be published as v2. Should be possible as a minor release though hopefully.

Also hey if you feel like it feel free to work on it and shoot me a PR! :)

**Comment by iqbalhussain931** [comment]
I understand sure that your time @bkrem and though i am at a beginners level on react but would loved to be a part of this but surely will need your help too :)

**Comment by iqbalhussain931** [comment]
Hey @bkrem 
how are you? :)
just wanted to take a follow up on the feature as discussed with you.

**Comment by bkrem** [comment]
Hey, haven’t had time during the week to work on the library but I’ll start on this tomorrow! 
Until I get paid for open source I unfortunately have to prioritise my job 😛

**Comment by henryhuang** [comment]
@bkrem , I need this feature, because currently the styles attr is static, i think the styles should be passed with object or function, if object then use current logic, but if function, it can pass linkData to the function to return styles object. Like path render function.

**Comment by bkrem** [comment]
Hey @henryhuang, yeah I feel your pain here. This project was originally adapted from a tight use case so there are still inflexible aspects that need ironing out.

At the moment I simply don't have the time to work on this properly due to requirements of my professional work + having 2 major features already as WIP for this project.
If you have the time to write an implementation that you think makes more sense as a whole that would be awesome!

Please be aware though that if it breaks the current `styles` API it'll have to go into v2 rather than as a v1.x release. If that's the case I'll clean up what's left of the v2 roadmap ASAP to push out that feature 👍

**Comment by bkrem** [comment]
Resolved in #82, closing.
