### ISSUE TITLE
Typings for hierarchyPointNode not working properly for me

### ISSUE THREAD

**Issue by transfer1992** [bkrem/react-d3-tree#357]
Thank you for taking the time to report an issue with react-d3-tree!  

Feel free to delete any questions that do not apply.

## Are you reporting a bug, or opening a feature request?
A bug
  
## What is the actual behavior/output?
`hierarchyPointNode` is of type `any` by default

## What is the behavior/output you expect?
It is typed properly

## Can you consistently reproduce the issue/create a reproduction case (e.g. on https://codesandbox.io)?
I can fix the issue by manually installing `@types/d3-hierarchy` in my mother project code.

## What version of react-d3-tree are you using?
3.1.0

## If react-d3-tree crashed with a traceback, please paste the full traceback below.
Nope

**Comment by bkrem** [comment]
Hi @transfer1992,

Thanks for pointing this out 🙏  `@types/d3-hierarchy` is the odd one out that needs to be a prod dependency not in `devDependencies`.

Fixed in [v3.1.1](https://github.com/bkrem/react-d3-tree/releases/tag/v3.1.1), should no longer need an explicit install of `@types/d3-hierarchy`.
