### ISSUE TITLE
Held back at React 16 due to peer dependencies

### ISSUE THREAD

**Issue by michaeljohansen** [bkrem/react-d3-tree#400]
`react-d3-tree` depends on `@bkrem/react-transition-group`, which has a peer dependency on React 16. Maybe the repo `@bkrem/react-transition-group` (which does not have issues) should be upgraded to support React 18 (or at least React 17), or this repo should depend on the original `react-transition-group` to stay up-to-date?

I could try to submit a PR, but would be great with a pointer regarding which path to take.

## What version of react-d3-tree are you using?
3.3.2

**Comment by bkrem** [comment]
Hi @michaeljohansen,

The original reason for forking the `react-transition-group` package was to monkey patch the additional peer dependency support for React 17 since the React team discontinued the v1 version of the package, so that's already there:
https://github.com/bkrem/react-transition-group/commit/ab91cf37ba1e90949f354fae4b9975144032a941

I've extended this to React 18 now, updated `@bkrem/react-transition-group` in `react-d3-tree`, tested against React 18 as a whole, and published a release: https://github.com/bkrem/react-d3-tree/releases/tag/v3.3.4

(see the full changelog for the `react-transition-group` change)

I've also updated the demo, which now runs against react@18.2.0 and react-d3-tree@3.3.4.

Please let me know if you're still seeing issues in 3.3.4 with react 18 peer deps 🙏 

---

### Bigger picture 

Overall this is of course just kicking the can down the road on finding a suitable replacement for `react-transition-group` for animations and refactoring towards it, or removing animation support completely. 

I'm way too busy with professional work for the former right now unfortunately and I'd like to avoid the latter for as long as possible, thus I'm informally extending the peer dependency support here again as long as it works 👍

**Comment by michaeljohansen** [comment]
That turn-around time though! It worked great, all warnings resolved. Thank you so much @bkrem ! 🤩
