### ISSUE TITLE
translate props can be %?

### ISSUE THREAD

**Issue by myangsc** [bkrem/react-d3-tree#49]
the translate now can only support px

**Comment by myangsc** [comment]
Simply, how I can make it center in the container as default

**Comment by bkrem** [comment]
Hey @myangsc,

Yeah this is a bit tricky since using relative measures with `translate()` on SVG elements isn't as straightforward as it is with CSS.

A way you can achieve what you're looking for is setting a ref on your treeContainer element (i.e. `ref={tc => this.treeContainer = tc}` and then measuring its dimensions once the component tree has mounted:

```js
  componentDidMount() {
    const dimensions = this.treeContainer.getBoundingClientRect()
    this.setState({
      translate: {
        x: dimensions.width / 2,
        y: dimensions.height / 2 
      }
    })
  }
```

where you'd pass `this.state.translate` as the tree's `translate` prop.

Tested this just and now it works fine. Let me know if you have issues with this, happy to help. Will also add this to the docs since I'm sure other people would like to use "relative" dimensions to position the graph too.

**Comment by myangsc** [comment]
Do something similar to ur suggestion, @bkrem thanks
