### ISSUE TITLE
Is there any method to render the node attributes as a ReactNode element?

### ISSUE THREAD

**Issue by jzoe** [bkrem/react-d3-tree#54]
- [ ] Implementation
- [ ] Unit test
- [ ] Docs

I want to render the node attributes as a card like below: 

![image](https://user-images.githubusercontent.com/11612990/33366738-26936d7a-d527-11e7-82aa-40bc475d98e1.png)

![image](https://user-images.githubusercontent.com/11612990/33366752-368154c2-d527-11e7-8332-8f6518b899b1.png)

Is there any one can help?

**Comment by bkrem** [comment]
Hey @jzoe,

This isn't possible at the moment unfortunately. We took a shot at it in when #36 came up, but there were issues with `ReactElement`s being parsed to JSON since they have circular references.

I know this would be a really useful & extensible feature, so I'll give it another shot with a different approach this week when I find some time to work on the library :)

**Comment by jzoe** [comment]
Use the  `ReactDOMServer.renderToStaticMarkup(...)` element to replace the `<text>{this.props.attributes ...}</text>` in `src/Node/index.js` ? @bkrem

**Comment by bkrem** [comment]
Good idea, feel free to give it a shot and see how it goes!

**Comment by bintoll** [comment]
I have done it using foreignObject, you can use my pr https://github.com/bkrem/react-d3-tree/pull/58

**Comment by bkrem** [comment]
@jzoe Implemented in v1.8.0 as `nodeLabelComponent`. 

There are some browser support caveats so please check the "Using ForeignObjects" section of the docs.
