### ISSUE TITLE
Too fast clicking brakes collapse

### ISSUE THREAD

**Issue by lubuger** [bkrem/react-d3-tree#89]
When clicking multiple times fast on node when collapsible is set to true, it breaks it totally, maybe setTimeout to halt animation and calculation and after do that?

**Comment by lubuger** [comment]
Duplicated

**Comment by nimitwalia89** [comment]
hello. may i know this issue is duplicate of which issue? because tree does break when we click on node too fast.. i just installed this yesterday

**Comment by bkrem** [comment]
@nimitwalia89 👉 #8

**Comment by nimitwalia89** [comment]
@bkrem thanks. So this will be resolved in v1.11? Also i noticed 1 thing. if we add multiple trees in different div wrappers zoom and drag only works on the 1st one.

**Comment by bkrem** [comment]
@nimitwalia89 yes, readdressing that ticket is the next priority for me.

Hmm interesting, haven't come across that yet but I have an intuitive idea of what the issue might be here due to the way D3 does DOM node selection.

Could you please open an issue for this, briefly describing what the reproduction case would be? :)
